inc/mtp.h

This fixes the build under GCC 8 with the musl C library.
Signed-off-by: Paul Cercueil <paul@crapouillou.net>

Add missing <pthread.h> include in inc/mtp.h header

---

src/mtp_operations/mtp_op_sendobject.c

Add missing <sys/stat.h> include, required to use S_IRUSR / S_IWUSR.
Signed-off-by: Paul Cercueil <paul@crapouillou.net>

mtp_operations: Add missing include

---

conf/umtprd.conf
inc/mtp.h
src/mtp_cfg.c
src/mtp_datasets.c

This PR adds firmware version as a configuration item so a custom firmware version can be displayed when querying MTP properties.

Add custom firmware version configuration item

---

src/fs_handles_db.c

This fixes a crash for me from issue #29 when ejecting the removable storage media while not attached to a host.

Check that fs handles db is valid before using it to get entries

---

src/inotify.c

renames the file on the MTP responder side, and the MTP Initiator side also can update.
Signed-off-by: zhy <1171892158@qq.com>

Supports renaming files on MTP Responder side

---

src/fs_handles_db.c

closedir(NULL) causes a segmentation fault within uClibc.
Signed-off-by: Paul Cercueil <paul@crapouillou.net>

src/fs_handles_db.c: Fix segmentation fault

---

inc/mtp.h
src/mtp_cfg.c
src/mtp_datasets.c

This flag can be used to tell that a storage should be seen as
removable.
This flag changes the storage type from MTP_STORAGE_FIXED_RAM (0x3)
to MTP_STORAGE_REMOVABLE_RAM (0x4).
Signed-off-by: Paul Cercueil <paul@crapouillou.net>

Add "removable" flag to storages

---

inc/mtp.h
inc/mtp_cfg.h
src/msgqueue.c
src/mtp.c
src/mtp_cfg.c

These two commands allow to dynamically add and remove storages.
This is useful e.g. when the storage mountpoints and/or names are not known in advance.

Add addstorage/rmstorage commands

---

src/mtp_operations/mtp_op_getobjecthandles.c

When using multiple storages, changes in some of the root folders can't be seen at the initiator (observed with Windows 10 and Ubuntu 18.04). This seems to be caused by a wrong assignment of the inotify watch descriptor for the root directories.
In mtp_op_GetObjectHandles() the entry object was always retrieved by calling get_entry_by_handle() with the parent_handle == 0. Thus always the same entry was returned for all storages and the inotify watch descriptors for the root folders got assigned always to the same entry.

Fix inotify for root folders when using multiple storages

---

Makefile

Object file targets need to depend on the output_dir target.
Fixes:
```
make --shuffle=reverse -j1
cc -o obj/mtp_op_truncateobject.o src/mtp_operations/mtp_op_truncateobject.c -c  -I./inc -lpthread -Wall -O3 Assembler messages:
Fatal error: can't create obj/mtp_op_truncateobject.o: No such file or directory
make: *** [Makefile:19: obj/mtp_op_truncateobject.o] Error 1 shuffle=reverse
```

Fix output_dir make dependency

---

src/fs_handles_db.c

When umtp encounters a directory with a dangling symlink, it would wrongly presume an access issue, log and error:
MTP_OPERATION_GET_OBJECT_HANDLES : FOLDER ACCESS ERROR ! 
and the host/client would throw an "Input/output error" at the user.
The fix is rather straight-forward: have the "fs_find_first_file" actually iterate over the entries returned by "readdir", and not just stop at the (possibly broken) first.
Also log the error as PRINT_WARNING in the daemon's log output, so that a user can diagnose&fix the issue.
----
```
mkdir -p /mnt/data/mtp-storage/symlink
echo aaa >  /mnt/data/mtp-storage/symlink/AAA
ln -s /tmp/bbb  /mnt/data/mtp-storage/symlink/BBB
echo ccc >  /mnt/data/mtp-storage/symlink/CCC
$host> ls mtp-mountpoint/symlink/
AAA 
CCC
```

Fix dangling symlinks handling

---

conf/umtprd.conf
inc/mtp.h
src/mtp_cfg.c
src/mtp_operations/mtp_op_sendobject.c

On a non-battery-powered device (or a device that can be powered off by, say, a hardware power cut-off switch), data loss could occur because file buffer in RAM cannot be fully written to the internal storage before kernel-not-expected power off.
Without this patch, such device can only set their storage into sync mode to ensure all data are written to storage without caching, and that greatly reduce the write performance.
This PR includes:
1. add fsync() before close() call in mtp_op_SendObject(), to ensure all bytes received are written to the storage before the file is closed.
2. a variable "sync_when_close" in the ctx, and an option in the config to enable/disable this option. (Default is disabled to retain current behavior)

Add option to call fsync() before close() during mtp_op_SendObject()

---

inc/default_cfg.h

The built-in default config used /dev/ffs-umtp/ as the path to the endpoints, whereas both the sample umtprd.conf file and the umtprd-ffs.sh file used /dev/ffs-mtp/.
Change the built-in default config to also use /dev/ffs-mtp, so that the startup script can be used out of the box without having to put the config file in /etc.

Update USB device paths in built-in config

---

src/mtp.c
src/mtp_cfg.c
src/mtp_operations/mtp_op_sendobject.c

On linux files are usually created with permissions set to 666+umask, and folders with 777+umask.
The codebase used to create files with 600 and folders with 700 *unless* a umask override was set in the configuration, then both files and folders would end up with 777+umask.
This patch addresses this by setting the umask override on process level; Creating files with permissions set to 666 and folders set to 777 - with either the overridden or the system default umask applied.

fix default permissions and umask handling

---

src/mtp.c

Update the various mtp_get_storage_* functions so that they only print one debug line per call instead of two.

Reduce logging

---

src/usb_gadget.c

from one of our contractors:
```
umtp-responder: fix super-speed handling
Add the patches required to configure the USB SuperSpeed descriptors
correctly. Without the patches the host USB SuperSpeed negotiation fails
and the USB OTG mechanism (autom. host<->device switch) fails too.
Signed-off-by: Marco Felsch <m.felsch@pengutronix.de>
```

fix super-speed handling

---

src/usb_gadget.c

(errno == EAGAIN) was checked twice, where it should have been checking for EAGAIN or EWOULDBLOCK.

Fix copy/paste error

---

src/usb_gadget.c

On our machine, the original timeout is insufficient, causing the USB gadget to close when attempting to cancel a file transfer. We've extended the timeout with additional redundancy to prevent this from happening.

increase the cancel wait time between thread

---

Makefile
src/inotify.c
src/msgqueue.c

Make it more obvious that these functions are only used in their respective C files.

Make some functions static

---

inc/logs_out.h

The function-like PRINT_* macros would build differently for different build options, such that something like:
if (condition)
PRINT_MSG("yes")
else
PRINT_MSG("no")
(note the missing semicolons)
would build successfully with no additional build flags or with DEBUG=1, but would fail to compile with USE_SYSLOG=1.
This change makes it so that all build options cause the above to fail, same as if it had been a regular function call.

Make PRINT_* macros behave consistently

---

inc/msgqueue.h
src/msgqueue.c
src/umtprd.c

Make it possible to specify multiple -cmd: parameters at once, and to specify them when starting umtprd, e.g. instead of doing
umtrpd &
umtprd '-cmd:addstorage:/home Home rw'
umtprd '-cmd:addstorage:/data Data ro'
you can now do:
umtprd '-cmd:addstorage:/home Home rw' '-cmd:addstorage:/data Data ro'
Also make it so the order of parameters doesn't matter, i.e. specifying "-conf" before "-cmd:" will work as one might expect.

Rework command line argument handling

---

inc/fs_handles_db.h
src/fs_handles_db.c
src/mtp_operations/mtp_op_endeditobject.c
src/mtp_operations/mtp_op_sendobject.c
src/mtp_operations/mtp_ops_helpers.c

The current implementation that handles `MTP_OPERATION_SEND_PARTIAL_OBJECT` would repeatedly `open;write;close` during a transfer of a large file.
Which is undesirable when other processes in the system want to register with inotify to watch create/modify/close on a folder/file where access is provided over mtp.
The solution implemented here is to simply keep the file-descriptors around and open over the stream of `SendPartialObject` chunks.
The order of [MTP operations](https://en.wikipedia.org/wiki/Media_Transfer_Protocol#Android_extensions) is (or seems to be, always?):
`BeginEditObject`, `SendPartialObject` x chunk-size, `EndEditObject`.
Now the first SendPartial would open() the file, and the trailing EndEdit would then close() it. 
```
$> inotifywatch /mnt/data/mtp-storage/
total …
```

fix open-write-close chatter during SendObject 

---

conf/umtprd.conf
inc/mtp.h
inc/mtp_constant_strings.h
src/mtp_cfg.c
src/mtp_constant_strings.c
src/mtp_datasets.c

Remove legacy MTP extension string ("microsoft.com: 1.0; android.com: 1.0;") from DevInfos_MTP_Extensions[] and set it to an empty string. These identifiers were originally intended to point to vendor-specific documentation per the MTP spec [1], but no such documentation exists — even the Internet Archive has no record of it.
This string inadvertently triggers libmtp's [2] vendor-specific quirk handling, which includes problematic flags such as:
- DEVICE_FLAG_UNLOAD_DRIVER
- DEVICE_FLAG_FORCE_RESET_ON_CLOSE
These flags are applied when libmtp detects an "Android device" and assigns default bug flags [3], causing the USB connection to be reset after each transfer. This behavior is especially disruptive on multi-function USB devices, where the USB-gadget interface also serves as e.g. the …

datasets: deviceinfo: clear MTP extension string to avoid libmtp quirks and USB resets
